# -*- coding: utf-8 -*-
"""
/***************************************************************************
 wtyka2
                                 A QGIS plugin
 Wtyczka zalicza drugi projekt
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-04
        copyright            : (C) 2024 by Jakub i Adam
        email                : kubafajfer59@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load wtyka2 class from file wtyka2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .zaliczka import wtyka2
    return wtyka2(iface)
