# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zaliczka_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wtyka2DialogBase(object):
    def setupUi(self, wtyka2DialogBase):
        wtyka2DialogBase.setObjectName("wtyka2DialogBase")
        wtyka2DialogBase.resize(400, 300)
        self.comboBox = QtWidgets.QComboBox(wtyka2DialogBase)
        self.comboBox.setGeometry(QtCore.QRect(30, 30, 73, 22))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(wtyka2DialogBase)
        self.label.setGeometry(QtCore.QRect(150, 80, 55, 16))
        self.label.setObjectName("label")
        self.pbtnroznicaH = QtWidgets.QPushButton(wtyka2DialogBase)
        self.pbtnroznicaH.setGeometry(QtCore.QRect(120, 30, 93, 28))
        self.pbtnroznicaH.setObjectName("pbtnroznicaH")
        self.pushButton_2 = QtWidgets.QPushButton(wtyka2DialogBase)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 30, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(wtyka2DialogBase)
        QtCore.QMetaObject.connectSlotsByName(wtyka2DialogBase)

    def retranslateUi(self, wtyka2DialogBase):
        _translate = QtCore.QCoreApplication.translate
        wtyka2DialogBase.setWindowTitle(_translate("wtyka2DialogBase", "wtyka2"))
        self.label.setText(_translate("wtyka2DialogBase", "WYNIK"))
        self.pbtnroznicaH.setText(_translate("wtyka2DialogBase", "Różnica H"))
        self.pushButton_2.setText(_translate("wtyka2DialogBase", "Pole"))
