# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zaliczka_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wtyka2DialogBase(object):
    def setupUi(self, wtyka2DialogBase):
        wtyka2DialogBase.setObjectName("wtyka2DialogBase")
        wtyka2DialogBase.resize(408, 318)
        self.wynikroznicyh = QtWidgets.QLabel(wtyka2DialogBase)
        self.wynikroznicyh.setGeometry(QtCore.QRect(140, 120, 55, 16))
        self.wynikroznicyh.setText("")
        self.wynikroznicyh.setObjectName("wynikroznicyh")
        self.pbtnroznicaH = QtWidgets.QPushButton(wtyka2DialogBase)
        self.pbtnroznicaH.setGeometry(QtCore.QRect(260, 80, 93, 28))
        self.pbtnroznicaH.setObjectName("pbtnroznicaH")
        self.pbpole = QtWidgets.QPushButton(wtyka2DialogBase)
        self.pbpole.setGeometry(QtCore.QRect(260, 160, 93, 28))
        self.pbpole.setObjectName("pbpole")
        self.wynikpola = QtWidgets.QLabel(wtyka2DialogBase)
        self.wynikpola.setGeometry(QtCore.QRect(130, 210, 55, 16))
        self.wynikpola.setText("")
        self.wynikpola.setObjectName("wynikpola")
        self.layer = QgsMapLayerComboBox(wtyka2DialogBase)
        self.layer.setGeometry(QtCore.QRect(110, 10, 181, 51))
        self.layer.setObjectName("layer")
        self.btnbx = QtWidgets.QDialogButtonBox(wtyka2DialogBase)
        self.btnbx.setGeometry(QtCore.QRect(100, 270, 193, 28))
        self.btnbx.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnbx.setCenterButtons(False)
        self.btnbx.setObjectName("btnbx")
        self.lblwysinfo = QtWidgets.QLabel(wtyka2DialogBase)
        self.lblwysinfo.setGeometry(QtCore.QRect(10, 70, 251, 51))
        self.lblwysinfo.setObjectName("lblwysinfo")
        self.lblpoleinfo = QtWidgets.QLabel(wtyka2DialogBase)
        self.lblpoleinfo.setGeometry(QtCore.QRect(10, 150, 251, 51))
        self.lblpoleinfo.setObjectName("lblpoleinfo")

        self.retranslateUi(wtyka2DialogBase)
        self.btnbx.accepted.connect(wtyka2DialogBase.accept) # type: ignore
        self.btnbx.rejected.connect(wtyka2DialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(wtyka2DialogBase)

    def retranslateUi(self, wtyka2DialogBase):
        _translate = QtCore.QCoreApplication.translate
        wtyka2DialogBase.setWindowTitle(_translate("wtyka2DialogBase", "wtyka2"))
        self.pbtnroznicaH.setText(_translate("wtyka2DialogBase", "Różnica H"))
        self.pbpole.setText(_translate("wtyka2DialogBase", "Pole"))
        self.lblwysinfo.setText(_translate("wtyka2DialogBase", "W celu obliczenia różnicy wysokości kliknij:"))
        self.lblpoleinfo.setText(_translate("wtyka2DialogBase", "W celu obliczenia pola kliknij:"))
from qgsmaplayercombobox import QgsMapLayerComboBox
