# -*- coding: utf-8 -*-
"""
/***************************************************************************
 wtyczkap2
                                 A QGIS plugin
 Wtyczka zalicza projekt drugi
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-04
        copyright            : (C) 2024 by Buława Adam, Jakub Fajfer
        email                : kubafajfer59@gmai.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load wtyczkap2 class from file wtyczkap2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .wtyczkap2 import wtyczkap2
    return wtyczkap2(iface)
