# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wtyczkap2_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wtyczkap2DialogBase(object):
    def setupUi(self, wtyczkap2DialogBase):
        wtyczkap2DialogBase.setObjectName("wtyczkap2DialogBase")
        wtyczkap2DialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(wtyczkap2DialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")

        self.retranslateUi(wtyczkap2DialogBase)
        self.button_box.accepted.connect(wtyczkap2DialogBase.accept) # type: ignore
        self.button_box.rejected.connect(wtyczkap2DialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(wtyczkap2DialogBase)

    def retranslateUi(self, wtyczkap2DialogBase):
        _translate = QtCore.QCoreApplication.translate
        wtyczkap2DialogBase.setWindowTitle(_translate("wtyczkap2DialogBase", "wtyczkap2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wtyczkap2DialogBase = QtWidgets.QDialog()
    ui = Ui_wtyczkap2DialogBase()
    ui.setupUi(wtyczkap2DialogBase)
    wtyczkap2DialogBase.show()
    sys.exit(app.exec_())
